version: '4.28'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=testovoe
      - POSTGRES_USER=testovoe
      - POSTGRES_PASSWORD=testovoe
  web:
    build: testovoe_docker
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
